### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by priyankartalukdar** [bwghughes/spc#1]
Issue:  TypeError: parse_requirements() missing 1 required keyword argument: 'session'

I tried adding session = 'None' with no help. Is there a workaround to the problem?

**Comment by RVPLiu** [comment]
I got this error too.

**Comment by bwghughes** [comment]
Hi folks, sorry this has been here for so long - will look at now.

**Comment by bwghughes** [comment]
Looks to be a breaking change with pip around the `parse_requirements` feature. Investigating.

**Comment by bwghughes** [comment]
Please retest - bumped version to 0.23 on pypi to fix. Will close on confirmation of fix.

**Comment by bwghughes** [comment]
Confirmed as fixed.
